# Generated by Django 5.0.3 on 2024-03-24 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=2)),
                ('continent', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=30)),
                ('description_job', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=14)),
                ('full_name', models.CharField(max_length=20)),
                ('surname', models.CharField(blank=True, max_length=10, null=True)),
                ('address_street', models.CharField(max_length=50)),
                ('address_number', models.CharField(max_length=7)),
                ('postal_code', models.CharField(max_length=10)),
                ('telephone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_registration', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees_city', to='employees.cities')),
                ('position_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees_job', to='employees.job')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=2)),
                ('region', models.CharField(max_length=20)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_country', to='employees.countries')),
            ],
        ),
        migrations.AddField(
            model_name='cities',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_state', to='employees.state'),
        ),
    ]
